# Generated by Django 4.1 on 2022-09-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='celular',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='foto_perfil',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
