# Generated by Django 4.1 on 2022-09-21 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estaAceptado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('fecha', models.DateField(blank=True, default=None, null=True)),
                ('hora', models.TimeField(blank=True, default=None, null=True)),
                ('imagen_vehiculo', models.ImageField(upload_to='images/')),
                ('descripcion', models.CharField(max_length=250)),
                ('capacidad', models.PositiveIntegerField()),
                ('ocupados', models.PositiveIntegerField(default=0)),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_destino_set', to='viajes.ciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_origen_set', to='viajes.ciudad')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_set', to=settings.AUTH_USER_MODEL)),
                ('pasajeros', models.ManyToManyField(through='viajes.UsuarioPeticion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuariopeticion',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.provincia'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('conductor', 'datetime'), name='unique_conductor_datetime_combination'),
        ),
        migrations.AddConstraint(
            model_name='usuariopeticion',
            constraint=models.UniqueConstraint(fields=('viaje', 'user'), name='unique_viaje_user_combination'),
        ),
    ]
