# Generated by Django 4.1 on 2022-09-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_usuariopeticion_estaaceptado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopeticion',
            old_name='estaAceptado',
            new_name='esta_aceptado',
        ),
    ]
