# Generated by Django 4.1 on 2022-09-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_conductor_celular_alter_conductor_foto_perfil'),
        ('viajes', '0003_rename_estaaceptado_usuariopeticion_esta_aceptado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_set', to='users.conductor'),
        ),
    ]
