# Generated by Django 4.1 on 2022-10-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_alter_viaje_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='ocupados',
        ),
    ]
