# Generated by Django 4.1 on 2022-10-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_remove_viaje_ocupados'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='disponible',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
