# Generated by Django 4.1 on 2022-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.CharField(max_length=60),
        ),
    ]
