# Generated by Django 4.1 on 2022-09-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_viaje_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
