# Generated by Django 4.1 on 2022-08-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
