# Generated by Django 4.1 on 2022-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_viaje_fecha_alter_viaje_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
