# Generated by Django 4.1 on 2022-08-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_rename_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ConfirmPassword',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
