# Generated by Django 4.1 on 2022-08-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
