# Generated by Django 4.1 on 2022-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_usuariopeticion_remove_viaje_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
