# Generated by Django 4.1 on 2022-09-16 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sitio', '0005_alter_viaje_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='pasajeros',
            field=models.ManyToManyField(through='sitio.UsuarioPeticion', to=settings.AUTH_USER_MODEL),
        ),
    ]
