# Generated by Django 4.1 on 2022-09-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_dtmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTModel',
        ),
    ]
