# Generated by Django 4.1 on 2022-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_viaje_imagen'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viaje',
            name='unique_conductor_fecha_combination',
        ),
        migrations.AddField(
            model_name='viaje',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('conductor', 'datetime'), name='unique_conductor_fecha_combination'),
        ),
    ]
