# Generated by Django 4.1 on 2022-09-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_remove_viaje_unique_conductor_fecha_combination_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viaje',
            name='unique_conductor_fecha_combination',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='hora',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('conductor', 'datetime'), name='unique_conductor_datetime_combination'),
        ),
    ]
