# Generated by Django 4.1 on 2022-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_remove_viaje_unique_conductor_fecha_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
